### ISSUE TITLE
prism不起作用

### ISSUE THREAD

**Issue by TheNetAdmin** [ele828/hexo-prism-plugin#5]
我尝试将prism_plugin的设置代码插入到`/_config.yml`或者`/theme/some_theme/_config.yml`，但是实际生成的页面并没有prism高亮的代码块

**Comment by sn0wle0pard** [comment]
Did you check  `highlight: enable: false` in `/_config.yml`?  hexo-prism-plugin only work turn false

**Comment by cubesky** [comment]
I turned
```yml
highlight:
  enable: false
```
and add 
```yml
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess 
  theme: 'default'
  line_number: true
```
to `_config.yml` in the site config.
But it doesn't work.
![image](https://cloud.githubusercontent.com/assets/8038511/23034721/af172cbe-f4b7-11e6-931a-90e90f3cf9eb.png)

I try to generate with `hexo clean&hexo g` and `hexo clean&hexo s` it doesn't work.

**Comment by cubesky** [comment]
`line_number` option not work too, but I try to add a `!important` in `line-numbers.css` line number is shown.
![image](https://cloud.githubusercontent.com/assets/8038511/23035834/7d5b5d7c-f4bb-11e6-9227-2a30254b59b7.png)

But highlight not work yet.

**Comment by ele828** [comment]
@TheNetAdmin @cubesky I just released hexo-prism-plugin V2.0, please try to install it again.

If you still couldn't make it, just let me know more details, and I will fix it.

Thanks :)

**Comment by kuuhaku-w** [comment]
The error description is "Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin." That troubled me a lot and I still can't sovle it yet.

**Comment by STCloudLake** [comment]
> The error description is "Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin." That troubled me a lot and I still can't sovle it yet.

The same to me, and I test lots of combo cases but no one works, either it will cause a fatal error or it runs but doesn't work correctly. I'm tired of this. :(

**Comment by ghost** [comment]
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.

**Comment by EarendelH** [comment]
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.

The same error to me
